Repository mongodb/docs-meta, pull requests merged in 2020-07, with the labels that each got.

#55 (DOCSP-11383) Update time and space page
  source/style-guide/terminology/general-term-guidelines/use-consistent-time-references.txt
Labels: RFM, feature

#58 (DOCSP-11377) Update Product Names and Versions page
  source/style-guide/style/product-names-version-numbers.txt
Labels: copy review, feature

#60 (DOCSP-11382) Update short words page
  source/style-guide/terminology/general-term-guidelines/use-short-words.txt
Labels: RFM, feature

#59 (DOCSP-11404) API placeholders
  source/style-guide/style/cloud-account-info.txt
Labels: RFM, feature

#56 (DOCSP-11376) Update lists page
  source/style-guide/style/lists.txt
Labels: RFM, feature

#57 (DOCSP-11375) Update Links page
  conf.py
  config/intersphinx.yaml
  source/style-guide/style/links-and-cross-references.txt
Labels: RFM, feature

#54 (DOCSP-11379) Update Titles and Heading page
  source/style-guide/style/titles-and-headings.txt
Labels: RFM, feature

#62 (DOCSP-11381) Update URLs page
  source/style-guide/style/urls.txt
Labels: RFM, feature

#53 (DOCSP-11374) Update IP Address page
  source/style-guide/style/ip-addresses.txt
Labels: RFM, feature

#52 (DOCSP-11372) Update Caps page
  source/style-guide/style/capitalization.txt
Labels: RFM, feature

#36 (DOCSP-11368) Update Present Tense page
  source/style-guide/writing/use-present-tense.txt
Labels: RFM, feature

#35 (DOCSP-11367) Update Use Active Voice page
  source/style-guide/writing/use-active-voice.txt
Labels: RFM, feature

#37 (DOCSP-11369) Update Person and Mood page
  source/style-guide/writing/use-effective-verbs.txt
  source/style-guide/writing/write-to-the-user.txt
Labels: RFM, feature, squash

#43 (DOCSP-11393): update Prepositions
  source/style-guide/style/prepositions.txt
Labels: copy review, feature

#42 (DOCSP-11391): Update Names to include diversity
  source/style-guide/style/names.txt
Labels: copy review, feature

#41 (DOCSP-11410): Removed blog guidelines
  source/style-guide.txt
  source/style-guide/blog-guidelines.txt
Labels: feature

#47 (DOCSP-11397): Add 'Considerations' to Tasks page
  source/style-guide/style/tasks.txt
Labels: feature

#46 (DOCSP-11409): Remove How-To Guidelines page
  source/style-guide.txt
  source/style-guide/how-to-article-guidelines.txt
Labels: feature

#45 (DOCSP-11403): Update Write for Accessibility
  source/style-guide/writing/write-for-accessibility.txt
Labels: feature

#49 (DOCSP-11371) Update abbreviations page
  source/style-guide/style/abbreviations.txt
Labels: RFM, feature

#48 (DOCSP-11370) Update concise content page
  source/style-guide/writing/write-clear-concise-sentences-paragraphs.txt
Labels: RFM, feature

#67 (DOCSP-11406): Update Email Addresses page
  source/style-guide/style/email-addresses.txt
Labels: copy review, feature

#66 (DOCSP-11402): Remove repetition in Don't Humanize Inanimate Objects
  source/style-guide/writing/use-effective-verbs.txt
Labels: RFM, feature, squash

#65 (DOCSP-11398): Update Telephone Numbers page
  source/style-guide/style/telephone-numbers.txt
Labels: RFM, feature, squash

#63 (DOCSP-11392): Updated Call-outs page
  source/style-guide/style/callouts.txt
  source/style-guide/style/index.txt
  source/style-guide/style/notations.txt
  source/style-guide/style/tables.txt
Labels: RFM, feature, squash

#44 (DOCSP-11394): Update Punctuation page
  source/style-guide/style/punctuation.txt
Labels: RFM, feature, squash

#38 (DOCSP-11399): Update Voice & Tone w/ JD feedback
  source/style-guide/style/voice-and-tone.txt
Labels: RFM, feature, squash

#64 (DOCSP-11396): Update Tables page
  source/style-guide/style/punctuation.txt
  source/style-guide/style/tables.txt
Labels: copy review, feature
